language: node_js
node_js:
  - '0.10'

before_script: git clone $LAPIS_DEPLOY $DEPLOY_ROOT && eval $(ssh-agent) && $DEPLOY_ROOT/setup_git
script: npm run-script travis-deploy
after_script: eval $(ssh-agent -k)

branches:
  only: source

notifications:
  email: false

env:
  global:
    - LAPIS_DEPLOY=https://github.com/LapisBlue/Deploy.git DEPLOY_ROOT=/tmp/lapis/deploy
    - GIT_REPO=git@github.com:LapisBlue/lapisblue.github.io.git
    - secure: "Wkl2iDMv5K8q7yt8ocw/9ycnSeFuG/YAK6qaJ14lQkMnkISKPUKN0T3i1yQxXtKrkJLgV7fVBU7we9uCw2Ao9Es4kX9Jvwh9Gbkdbd0xPCW2CQqxbDh6xX8iXfQ7r/+BWIxDQwzVG5D1OBkZV1V5HBwLMakuE3G2+sC55b/Id8Q="
