language: node_js
node_js:
  - '0.10'
before_script: eval $(ssh-agent) && $DEPLOY_ROOT/setup_git.sh
script: npm run-script travis-deploy
after_script: eval $(ssh-agent -k)
branches:
  only: source
notifications:
  email: false
env:
  global:
    - LAPIS_DEPLOY=https://github.com/LapisBlue/Deploy.git DEPLOY_ROOT=/tmp/lapis/deploy
    - GIT_REPO=git@github.com:LapisBlue/lapisblue.github.io.git
    - secure: PQ/VMylyRn27eoeBLdzTrq1AGBtk4FZOxXvWGZtpmEfueG6r5tN76peqMWYiFKjQE0zoYtNt3QcrozKligIiSPKeuGCDu/ubC10kHk7+9bJuwUxHcVshljUY1JgnUMhK3Iuz6AiYXaiVczz7pCiwNx3wTbnY5IDdkk5kJIHhhOY=
